source: .
destination: ./_site
exclude:
  - _log
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
plugins: [jekyll-paginate]
layouts_dir: ./_layouts
timezone: Asia/Shanghai
highlighter: rouge
port: 4000
permalink: "/:year/:month/:day/:title:output_ext"
paginate: 5
#paginate_path: "blog/page:num"
lsi: true
