name:          因思而变

source:        .
destination:   ./_site
plugins:       ./_plugins
layouts:       ./_layouts
baseurl:       'http://www.xdanger.com'
include:       ['.htaccess']
exclude:       ['_log', 'CNAME']
keep_files:    ['files']
timezone:      Asia/Shanghai
pygments:      true

port:          4000
assets_prefix: '//res.xdcdn.net'
permalink:     '/:year/:month/:day/:title.html'
paginate:      5
lsi:           true
