name:          因思而变

source:        .
destination:   ../www
plugins:       ./_plugins
layouts:       ./_layouts
baseurl:       'http://www.xdanger.com'
include:       ['.htaccess']
exclude:       ['_log']
keep_files:    ['.git']
timezone:      Asia/Shanghai
pygments:      true

port:          4000
assets_prefix: '//res.xdcdn.net'
permalink:     '/:year/:month/:day/:title.html'
paginate:      5
#paginate_path: "blog/page:num"
lsi:           true
