name:          因思而变

source:        .
destination:   ./_site
plugins:       ./_plugins
layouts:       ./_layouts
include:       ['.htaccess']
exclude:       ['_log', 'CNAME']
keep_files:    ['.git', '.svn', 'files']
timezone:      Asia/Shanghai
pygments:      true

port:          4000
baseurl:       /
url:           http://localhost:4000
lsi:           false

permalink:     '/:year/:month/:day/:title.html'
paginate:      5
paginate_path: 'blog/page:num'

assets_prefix: '//res.xdcdn.net'
