name:          因思而变
gems:          [jekyll-paginate]
source:        .
destination:   ../www
plugins_dir:   ./_plugins
layouts_dir:   ./_layouts
baseurl:       'http://www.xdanger.com'
include:       ['.htaccess']
exclude:       ['_log']
keep_files:    ['.git']
timezone:      Asia/Shanghai
highlighter:   pygments

port:          4000
assets_prefix: '//ast.xdcdn.net'
permalink:     '/:year/:month/:day/:title.html'
paginate:      5
#paginate_path: "blog/page:num"
lsi:           true
