source: .
destination: ./_site
plugins: [jekyll-paginate]
layouts_dir: ./_layouts
exclude: ["_log"]
timezone: Asia/Shanghai
highlighter: rouge

port: 4000
permalink: "/:year/:month/:day/:title:output_ext"
paginate: 5
#paginate_path: "blog/page:num"
lsi: true
